"""remove the nullable

Revision ID: 0453ddea2598
Revises: da972ae34065
Create Date: 2017-01-12 15:47:03.481000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0453ddea2598'
down_revision = 'da972ae34065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competition_result', 'corporate_min_price_total',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('competition_result', 'corporate_min_price_volume',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('competition_result', 'created_time',
               existing_type=mysql.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('competition_result', 'personal_min_price_total',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('competition_result', 'personal_min_price_volume',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('competition_result', 'updated_time',
               existing_type=mysql.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competition_result', 'updated_time',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('competition_result', 'personal_min_price_volume',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('competition_result', 'personal_min_price_total',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('competition_result', 'created_time',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('competition_result', 'corporate_min_price_volume',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('competition_result', 'corporate_min_price_total',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
