"""add unique index

Revision ID: da972ae34065
Revises: a72cab16f595
Create Date: 2017-01-09 17:14:29.159000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da972ae34065'
down_revision = 'a72cab16f595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competition_result', 'created_time',
               existing_type=mysql.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('competition_result', 'updated_time',
               existing_type=mysql.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_competition_result_month'), 'competition_result', ['month'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competition_result_month'), table_name='competition_result')
    op.alter_column('competition_result', 'updated_time',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('competition_result', 'created_time',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
